### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by PhysicistProgs** [nickjmiller/pytest-fixtures#5]
Hello. I'm not sure I have rights to create an issue in this case. I apologize if i shouldn't do it.
I think this extension may be very useful for me, but I can't make it work. May be I do something wrong and someone could explain me what exactly.

1) I installed the extension
![image](https://user-images.githubusercontent.com/67951307/151730364-1491867c-5e3a-4f48-b3c6-1c61e5ee30c4.png)
2) got path of pytest
![image](https://user-images.githubusercontent.com/67951307/151730465-9ca375fd-ee1a-469c-9625-b3a0adaf9c1a.png)
3) set "python.testing.pytestPath" in settings.json
![image](https://user-images.githubusercontent.com/67951307/151730543-76134f26-f53d-483c-a9d1-37f95fa3727b.png)

But when I start typing fixture name I see no reaction (on screenshot below I'm trying it in  root_project_folder/tests/conftest.py):
![image](https://user-images.githubusercontent.com/67951307/151730636-67e3112c-ef87-4160-a6a5-4e3d3b30c7e0.png)

**Comment by dtczest** [comment]
Same, this isn't working for me either.

**Comment by nickjmiller** [comment]
Hi I just merged a pull request that fixed a parsing issue for certain versions of pytest. Try updating the extension to 0.1.12 and let me know if that fixes it. Otherwise can you paste the output from pytest-fixtures logs in the extension? Or `Log (Extension Host)` if it's not present?

**Comment by PhysicistProgs** [comment]
Hi, now it works! 
But there are two problems: 
1) It doesn't show fixture docstring, only suggest fixture name.
![image](https://user-images.githubusercontent.com/67951307/154177718-1280ca0b-9092-407a-a954-3dea54a50600.png)
2) It suggest only fixtures with function scope. 
![image](https://user-images.githubusercontent.com/67951307/154178415-e1ea0b4d-a3a6-497e-95f7-0a62455096ed.png)
![image](https://user-images.githubusercontent.com/67951307/154178465-e613501e-4b71-4d4e-aa51-8a8e3b9b4936.png)

**Comment by nickjmiller** [comment]
1 seems like a regression, 2 is an existing bug I will look into fixing these asap

**Comment by nickjmiller** [comment]
These both should be fixed in 0.1.13, let me know if it works. The formatting of the docstrings lost some style but I'll add it back later.

**Comment by nickjmiller** [comment]
Ah oops issue 2 is not quite fixed.

**Comment by PhysicistProgs** [comment]
Now it works with different scope of fixture
![image](https://user-images.githubusercontent.com/67951307/154183124-3d3761a4-0261-411b-be9f-5c711dee6b3f.png)

But I still can't see fixture documentation.
![image](https://user-images.githubusercontent.com/67951307/154183258-88978828-827d-41df-90cb-863adbed0d23.png)

**Comment by dtczest** [comment]
Still not working for me, 0.1.14:

```[2/16/2022 - 9:15:28 AM] File is a python test file, loading fixtures...
[2/16/2022 - 9:15:28 AM] Running command python -m pytest --color no --fixtures -v /Users/***/Documents/***/model-deploy-service/tests/test_deploy_manager.py in directory /Users/***/Documents/***/model-deploy-service/tests
[2/16/2022 - 9:15:28 AM] Found 0 fixtures
[2/16/2022 - 9:15:42 AM] Changed active file to extension-output-nickmillerdev.pytest-fixtures-#1, loading fixtures...```

But when I run that same command:
```(mds-377) *** model-deploy-service % python -m pytest --color no --fixtures -v /Users/***/Documents/***/model-deploy-service/tests/test_deploy_manager.py
============================================================================================================================= test session starts =============================================================================================================================
platform darwin -- Python 3.7.7, pytest-6.0.1, py-1.11.0, pluggy-0.13.1 -- /Users/***/miniconda3/envs/mds-377/bin/python
cachedir: .pytest_cache
rootdir: /Users/***/Documents/***/model-deploy-service
plugins: nbval-0.9.6, remotedata-0.3.1, cov-2.7.1, syrupy-1.7.3
collected 29 items
<redacted>


-------------------------------------------------------------------------------------------------------------------- fixtures defined from tests.conftest ---------------------------------------------------------------------------------------------------------------------
test_paths [module scope] -- tests/conftest.py:108
    tests/conftest.py:108: no docstring available

cleanup -- tests/conftest.py:113
    tests/conftest.py:113: no docstring available

rb_raw_data [session scope] -- tests/conftest.py:120
    tests/conftest.py:120: no docstring available

rb_raw_data_x_y [session scope] -- tests/conftest.py:129
    tests/conftest.py:129: no docstring available

rb_preprocessor_data [session scope] -- tests/conftest.py:138
    tests/conftest.py:138: no docstring available

dpt_pipe [session scope] -- tests/conftest.py:150
    tests/conftest.py:150: no docstring available

keras_pipe [session scope] -- tests/conftest.py:156
    tests/conftest.py:156: no docstring available

lem_model_pipe [session scope] -- tests/conftest.py:162
    tests/conftest.py:162: no docstring available

rb_payload_b_cb_json [module scope] -- tests/conftest.py:168
    tests/conftest.py:168: no docstring available

rb_payload_b_json [module scope] -- tests/conftest.py:175
    tests/conftest.py:175: no docstring available

rb_payload_cb_json [module scope] -- tests/conftest.py:182
    tests/conftest.py:182: no docstring available

rb_payload_json_v5 [module scope] -- tests/conftest.py:189
    tests/conftest.py:189: no docstring available

rb_batch_payload_json_v5 [module scope] -- tests/conftest.py:196
    tests/conftest.py:196: no docstring available

rb_batch_no_row_id_payload_json_v5 [module scope] -- tests/conftest.py:203
    tests/conftest.py:203: no docstring available

rb_batch_duplicate_row_id_payload_json_v5 [module scope] -- tests/conftest.py:211
    tests/conftest.py:211: no docstring available

rb_payload_csv_v5 [module scope] -- tests/conftest.py:219
    tests/conftest.py:219: no docstring available

rb_payload_csv_v5_no_tu [module scope] -- tests/conftest.py:226
    tests/conftest.py:226: no docstring available

dpt_training_ds [module scope] -- tests/conftest.py:234
    tests/conftest.py:234: no docstring available

dfff_json_payload [module scope] -- tests/conftest.py:240
    tests/conftest.py:240: no docstring available

rb_payload_json_v5_multi_index [module scope] -- tests/conftest.py:247
    tests/conftest.py:247: no docstring available

rb_payload_json_v5_batch_multi_index [module scope] -- tests/conftest.py:254
    tests/conftest.py:254: no docstring available

get_tz_xml_data_v5 [module scope] -- tests/conftest.py:261
    tests/conftest.py:261: no docstring available

get_csv_data_v5 [module scope] -- tests/conftest.py:268
    tests/conftest.py:268: no docstring available

get_csv_data_v4_person [module scope] -- tests/conftest.py:275
    tests/conftest.py:275: no docstring available

get_csv_data_v4_person_coperson [module scope] -- tests/conftest.py:282
    tests/conftest.py:282: no docstring available

get_tz_format_v5 [module scope] -- tests/conftest.py:289
    tests/conftest.py:289: no docstring available

get_official_data_v5__invalid [module scope] -- tests/conftest.py:296
    tests/conftest.py:296: no docstring available

get_official_data_v5__mixed_valid [module scope] -- tests/conftest.py:303
    tests/conftest.py:303: no docstring available

deployable_object [module scope] -- tests/conftest.py:310
    tests/conftest.py:310: no docstring available

deployable_object_with_preprocessor [module scope] -- tests/conftest.py:316
    tests/conftest.py:316: no docstring available

deployable_object_ens [module scope] -- tests/conftest.py:322
    tests/conftest.py:322: no docstring available

v5_path_type [module scope] -- tests/conftest.py:328
    tests/conftest.py:328: no docstring available

snapshot_json -- tests/conftest.py:36
    tests/conftest.py:36: no docstring available

generate_test_data_objects [session scope] -- tests/conftest.py:41
    tests/conftest.py:41: no docstring available

serialized_data_dir [module scope] -- tests/conftest.py:69
    tests/conftest.py:69: no docstring available

archive_dir -- tests/conftest.py:78
    tests/conftest.py:78: no docstring available

get_pii_file_path [module scope] -- tests/conftest.py:84
    tests/conftest.py:84: no docstring available

data [module scope] -- tests/conftest.py:89
    tests/conftest.py:89: no docstring available


--------------------------------------------------------------------------------------------------------------- fixtures defined from tests.test_deploy_manager ---------------------------------------------------------------------------------------------------------------
toy_path_type [module scope] -- tests/test_deploy_manager.py:104
    tests/test_deploy_manager.py:104: no docstring available

archive_path_type [module scope] -- tests/test_deploy_manager.py:109
    tests/test_deploy_manager.py:109: no docstring available

queue_archive_path_type [module scope] -- tests/test_deploy_manager.py:120
    tests/test_deploy_manager.py:120: no docstring available

queue_archive_path_exclude [module scope] -- tests/test_deploy_manager.py:132
    tests/test_deploy_manager.py:132: no docstring available

queue_archive_snapshot_args [module scope] -- tests/test_deploy_manager.py:139
    tests/test_deploy_manager.py:139: no docstring available

ready_endpoint_from_deploy_manager -- tests/test_deploy_manager.py:144
    tests/test_deploy_manager.py:144: no docstring available

deployable_toy_object [module scope] -- tests/test_deploy_manager.py:19
    tests/test_deploy_manager.py:19: no docstring available

queue_archiver -- tests/test_deploy_manager.py:25
    tests/test_deploy_manager.py:25: no docstring available

deploy_manager_fs -- tests/test_deploy_manager.py:30
    tests/test_deploy_manager.py:30: no docstring available

deploy_manager_fs_sync -- tests/test_deploy_manager.py:42
    tests/test_deploy_manager.py:42: no docstring available

deploy_manager_ens_queue_sync -- tests/test_deploy_manager.py:51
    tests/test_deploy_manager.py:51: no docstring available

deploy_manager_toy_fs -- tests/test_deploy_manager.py:64
    tests/test_deploy_manager.py:64: no docstring available

deploy_manager_toy_fs_sync -- tests/test_deploy_manager.py:76
    tests/test_deploy_manager.py:76: no docstring available

extract_app_id_from_row_ids -- tests/test_deploy_manager.py:89
    tests/test_deploy_manager.py:89: no docstring available

extract_app_id_from_raw_data -- tests/test_deploy_manager.py:94
    tests/test_deploy_manager.py:94: no docstring available

extract_app_id_from_request_id -- tests/test_deploy_manager.py:99
    tests/test_deploy_manager.py:99: no docstring available


--------------------------------------------------------------------------------------------------------------------------- snapshot report summary ---------------------------------------------------------------------------------------------------------------------------

============================================================================================================================ no tests ran in 0.28s ============================================================================================================================```

**Comment by nickjmiller** [comment]
@dtczest I think this is a regression from using the cwd, I think it is looking in `/model-deploy-service/tests/tests/conftest.py`. I am not sure why this is the case but I can at least add some exception handling to resolve the autocompletion if the goto definition is broken while I investigate.

@PhysicistProgs can you paste the output of pytest fixtures command similarly to above?

**Comment by PhysicistProgs** [comment]
This is my file now: 

```python
import pytest


@pytest.fixture(scope='module')
def my_fix():
    """Fixture docs"""
    return 1


@pytest.fixture()
def another_fixture_with_big_docstring():
    """
    Some words about this fixture
    """


def test_func(my_fix):
    print(1)
```

This is the result, but only part about fixtures in this file: 
```
------------------------------------------------------------------------------------------- fixtures defined from tests.test_1 -------------------------------------------------------------------------------------------
another_fixture_with_big_docstring -- tests/test_1.py:11
    Some words about this fixture

my_fix [module scope] -- tests/test_1.py:5
    Fixture docs
```

**Comment by fredrikaverpil** [comment]
I'm on macOS and I'm getting:

```bash
[3/15/2022 - 9:09:57 PM] Active file is /Users/fredrik/code/repos/[redacted]/tests/test_logger.py, loading fixtures...
[3/15/2022 - 9:09:57 PM] File is a python test file, loading fixtures...
[3/15/2022 - 9:09:57 PM] Running command python -m pytest --color no --fixtures -v /Users/fredrik/code/repos/[redacted]/tests/test_logger.py in directory /Users/fredrik/code/repos/[redacted]/tests
[3/15/2022 - 9:09:57 PM] Found 0 fixtures
```

But if I run the command in my terminal (venv activated), I get loads of fixtures listed.

What could be wrong?

**Comment by nickjmiller** [comment]
Hi @fredrikaverpil can you paste the output of `python -m pytest --color no --fixtures -v /Users/fredrik/code/repos/[redacted]/tests/test_logger.py` using your venv? Do you have a `_pytest` folder? Do those paths make sense?

**Comment by fredrikaverpil** [comment]
@nickjmiller that command will print all fixtures available to pytest, including builtins and my own. So this command, I believe, output the right thing.

Here's a tail:

```
---------------------------------------- fixtures defined from pytest_mock.plugin -----------------------------------------
class_mocker [class scope] -- .venv/lib/python3.10/site-packages/pytest_mock/plugin.py:389
    Return an object that has the same interface to the `mock` module, but
    takes care of automatically undoing all patches after each test method.

mocker -- .venv/lib/python3.10/site-packages/pytest_mock/plugin.py:389
    Return an object that has the same interface to the `mock` module, but
    takes care of automatically undoing all patches after each test method.

module_mocker [module scope] -- .venv/lib/python3.10/site-packages/pytest_mock/plugin.py:389
    Return an object that has the same interface to the `mock` module, but
    takes care of automatically undoing all patches after each test method.

package_mocker [package scope] -- .venv/lib/python3.10/site-packages/pytest_mock/plugin.py:389
    Return an object that has the same interface to the `mock` module, but
    takes care of automatically undoing all patches after each test method.

session_mocker [session scope] -- .venv/lib/python3.10/site-packages/pytest_mock/plugin.py:389
    Return an object that has the same interface to the `mock` module, but
    takes care of automatically undoing all patches after each test method.


--------------------------------------------- fixtures defined from conftest ----------------------------------------------
_mocked_ddtrace -- tests/conftest.py:10
    no docstring available

_prod_env -- tests/conftest.py:23
    no docstring available

json_logger -- tests/conftest.py:28
    no docstring available

notify_logger -- tests/conftest.py:35
    no docstring available

capture_logs -- tests/conftest.py:44
    no docstring available


========================
```

I do not have a `_pytest` folder in that location. I believe it might be trying to access the internal `_pytest` module:

```python
import _pytest
```

**Comment by fredrikaverpil** [comment]
I'd really like to help to get this working. Let me know how I can help.

**Comment by dtczest** [comment]
@nickjmiller isn't this the problem?

```
        log(`Running command ${pythonPath} -m pytest ${args.join(" ")} in directory ${cwd}`);
        response = spawnSync(pythonPath, ["-m", "pytest", ...args], { cwd });
    } else {
        log(`Running command ${pytestPath} -m pytest ${args.join(" ")} in directory ${cwd}`);
        response = spawnSync(pytestPath, **args**, { shell: true, cwd });
```

**Comment by dtczest** [comment]
@nickjmiller I figured out the problem, though I'm not sure of the fix. I'm using conda environments, and my default environment doesn't have pytest installed. The correct conda environment for my workspace is not being used by the extension.

I added some logging to ALWAYS log stderr to the console:
```
[3/21/2022 - 9:31:38 AM] Active file is /Users/***/Documents/***/model-deploy-service/tests/test_app.py, loading fixtures... 
[3/21/2022 - 9:31:38 AM] File is a python test file, loading fixtures... 
[3/21/2022 - 9:31:38 AM] Running command python -m pytest --color no --fixtures -v /Users/***/Documents/***/model-deploy-service/tests/test_app.py in directory /Users/***/Documents/***/model-deploy-service 
[3/21/2022 - 9:31:38 AM] Pytest res: /Users/***/miniconda3/bin/python: No module named pytest
 
[3/21/2022 - 9:31:38 AM] Found 0 fixtures 
[3/21/2022 - 9:31:46 AM] Changed active file to extension-output-nickmillerdev.pytest-fixtures-#1, loading fixtures... 
```

So a few things from this:

1. response.error is not being set. Might you actually want to be checking for response.status === 1 and logging stderr?
2. The selected conda environment should be used to find the fixtures.

**Comment by nickjmiller** [comment]
@fredrikaverpil I just noticed in your output that it found 29 fixtures. I don't see anything wrong in the tail, are those fixtures working that you included? I'd be interested to see what the monkeypatch path looks like, and if pytest is outputting a rootDir (this should be at the top of the output).

@dtczest nice find, yeah I need to fix the logging there. I'm not too familiar with conda, but have you set your default python interpretter path in vscode to point to that env? Could you also set your `"python.testing.pytestPath"` to point at the pytest for your conda env?

**Comment by nickjmiller** [comment]
Ah I'm not sure when this happened but the extension is using an outdated method to find the python path of the selected interpreter. I will update this tonight

**Comment by fredrikaverpil** [comment]
> @fredrikaverpil I just noticed in your output that it found 29 fixtures. I don't see anything wrong in the tail, are those fixtures working that you included? 

Yes, those fixtures are working as expected.

> I'd be interested to see what the monkeypatch path looks like

```
monkeypatch -- .venv/lib/python3.10/site-packages/_pytest/monkeypatch.py:29
    A convenient fixture for monkey-patching.
    
    The fixture provides these methods to modify objects, dictionaries or
    os.environ::
    
        monkeypatch.setattr(obj, name, value, raising=True)
        monkeypatch.delattr(obj, name, raising=True)
        monkeypatch.setitem(mapping, name, value)
        monkeypatch.delitem(obj, name, raising=True)
        monkeypatch.setenv(name, value, prepend=None)
        monkeypatch.delenv(name, raising=True)
        monkeypatch.syspath_prepend(path)
        monkeypatch.chdir(path)
    
    All modifications will be undone after the requesting test function or
    fixture has finished. The ``raising`` parameter determines if a KeyError
    or AttributeError will be raised if the set/deletion operation has no target.
```

>  and if pytest is outputting a rootDir (this should be at the top of the output).

```
❯ python -m pytest --color no --fixtures -v /Users/fredrik/code/repos/[redacted]/tests/test_logger.py
=================================================== test session starts ===================================================
platform darwin -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0 -- /Users/fredrik/code/repos/[redacted]/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/fredrik/code/repos/[redacted]
plugins: mock-3.7.0, ddtrace-0.58.5
collected 1 item                                                                                                          
cache -- .venv/lib/python3.10/site-packages/_pytest/cacheprovider.py:510
    Return a cache object that can persist state between testing sessions.
    
    cache.get(key, default)
    cache.set(key, value)
    
    Keys must be ``/`` separated strings, where the first part is usually the
    name of your plugin or application to avoid clashes with other cache users.
    
    Values can be any object handled by the json stdlib module.
```

**Comment by nickjmiller** [comment]
This should be fixed in 0.1.19. I tested with venv and I think conda should work the same. For context the `pythonPath` variable was deprecated some time last year: https://github.com/microsoft/vscode-python/issues/12313#issuecomment-867932929

**Comment by fredrikaverpil** [comment]
@nickjmiller awesome, I now see autocompletion when starting to type something in the test function signature 👍 

However, I'm wondering if gotodef is working as expected?
Whenever I click "Go to definition" (F12), I get to see a menu which shows me there are two definitions. One in `conftest.py` and one in my test file. Is this expected?
Can I somehow make the extension ignore the definition in the test function signature, that I clicked?

**Comment by dtczest** [comment]
@nickjmiller thanks! I'm finding 93 fixtures now. I'm running into other issues, but I'll open separate issues for them.

**Comment by dtczest** [comment]
However, I am noticing that docstrings are not showing up for suggestions. However, this isn't limited to fixtures - I'm not seeing it for ANY function, in a test file or not. Is there something I need to enable in vscode for this?

**Comment by nickjmiller** [comment]
@fredrikaverpil Yeah this is a known issue with the microsoft python extension, which itself provides a definition that competes with this extension: https://github.com/microsoft/pylance-release/issues/2396. Yeah this is sort of a catch-all thread right now for issues.

@dtczest I'm not sure, but this sounds related to what @PhysicistProgs is seeing.

**Comment by nickjmiller** [comment]
I'm going to resolve this, I think the root cause for everyone was the pythonPath deteciton.

**Comment by dtczest** [comment]
Thanks for fixing this!

**Comment by fredrikaverpil** [comment]
@nickjmiller yes, many thanks for fixing this ⭐
